apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  # annotations:
#    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  selector:
    app: grpc-server
